apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deploy
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
        - name: data-volume
          mountPath: /data
      volumes:
      - name: html-volume
        configMap:
          name: nginx-html
      - name: data-volume
        persistentVolumeClaim:
          claimName: nginx-data
